"""Abstract base class for all EDA tool backends.

Every backend (ORFS, Innovus, ICC2, custom PR tool, …) must implement this
interface.  The agent core never imports a concrete backend directly – it
always works through this abstraction.
"""

from __future__ import annotations

import abc
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any


class StageStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class DesignSpec:
    """Describes a single RTL design to be implemented."""

    name: str
    """Human-readable design name / top-level module name."""

    config_path: Path
    """Path to the backend-specific design configuration file.
    For ORFS this is the ``DESIGN_CONFIG`` makefile fragment.
    For Innovus/ICC2 this could be a Tcl setup file."""

    pdk: str = ""
    """PDK / technology node identifier (e.g. 'sky130hd', 'asap7')."""

    rtl_hash: str = ""
    """Optional git / content hash of the RTL sources for traceability."""

    extra: dict[str, Any] = field(default_factory=dict)
    """Backend-specific extra fields."""


@dataclass
class RunResult:
    """Result returned after a backend stage completes (or fails)."""

    run_id: str
    """Unique identifier for this run (generated by the backend)."""

    backend_name: str
    design_name: str
    stage: str
    status: StageStatus
    started_at: datetime
    finished_at: datetime

    log_path: Path | None = None
    """Path to the captured stdout/stderr log file."""

    report_dir: Path | None = None
    """Directory where the backend placed output reports."""

    params: dict[str, Any] = field(default_factory=dict)
    """Parameters that were active for this run."""

    error_message: str = ""
    """Human-readable error description when status == FAILED."""


@dataclass
class ReportFile:
    """Metadata about a single report artefact produced by a stage."""

    path: Path
    report_type: str
    """Type tag: 'timing', 'congestion', 'utilization', 'power', etc."""

    stage: str
    run_id: str
    backend_name: str


class AbstractEDABackend(abc.ABC):
    """Contract that every EDA tool backend must fulfil.

    Implementations must be stateless with respect to individual runs so that
    multiple concurrent sessions can share the same backend instance safely.
    """

    # ------------------------------------------------------------------
    # Identification
    # ------------------------------------------------------------------

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Short identifier, e.g. 'orfs', 'innovus', 'icc2', 'custom_pr'."""

    @property
    @abc.abstractmethod
    def version(self) -> str:
        """Tool version string; may be determined at runtime."""

    # ------------------------------------------------------------------
    # Core interface
    # ------------------------------------------------------------------

    @abc.abstractmethod
    def get_supported_stages(self) -> list[str]:
        """Return the ordered list of flow stages this backend supports.

        Example (ORFS): ['synth', 'floorplan', 'place', 'cts', 'route', 'finish']
        """

    @abc.abstractmethod
    def run_stage(
        self,
        stage: str,
        design: DesignSpec,
        params: dict[str, Any],
    ) -> RunResult:
        """Execute a single flow stage and return a :class:`RunResult`.

        The implementation is responsible for:
        - Applying *params* to the tool invocation
        - Capturing logs to ``RunResult.log_path``
        - Placing output reports in ``RunResult.report_dir``
        - Setting ``RunResult.status`` accurately

        Raises
        ------
        ValueError
            If *stage* is not in :meth:`get_supported_stages`.
        RuntimeError
            If the backend executable is not found / not configured.
        """

    @abc.abstractmethod
    def collect_reports(self, result: RunResult) -> list[ReportFile]:
        """Scan ``result.report_dir`` and return structured :class:`ReportFile` list.

        This is called after :meth:`run_stage` returns successfully so the
        caller can hand off the files to the parser layer.
        """

    # ------------------------------------------------------------------
    # Optional helpers (provide sensible defaults)
    # ------------------------------------------------------------------

    def validate_params(self, stage: str, params: dict[str, Any]) -> dict[str, Any]:
        """Validate and normalise *params* for *stage*.

        The default implementation is a pass-through.  Override to add
        backend-specific validation / coercion.
        """
        if stage not in self.get_supported_stages():
            raise ValueError(
                f"Stage '{stage}' is not supported by backend '{self.name}'. "
                f"Supported: {self.get_supported_stages()}"
            )
        return params

    def is_available(self) -> bool:
        """Return True if the backend executable / environment is available."""
        return True

    def __repr__(self) -> str:
        return f"<{type(self).__name__} name={self.name!r} version={self.version!r}>"
